from django.urls import path
from . import views

urlpatterns = [
    path("dashboard/admin/", views.dashboard_admin, name="dashboard_admin"),
    path("dashboard/docente/", views.dashboard_docente, name="dashboard_docente"),
    path("dashboard/estudiante/", views.dashboard_estudiante, name="dashboard_estudiante"),
    path("cursos/", views.curso_lista, name="curso_lista"),
    path("cursos/<int:pk>/", views.curso_detalle, name="curso_detalle"),
    path("cursos/nuevo/", views.curso_crear, name="curso_crear"),
    path("cursos/<int:pk>/editar/", views.curso_editar, name="curso_editar"),
    path("cursos/<int:pk>/eliminar/", views.curso_eliminar, name="curso_eliminar"),
    path("materias/", views.materia_lista, name="materia_lista"),
    path("materias/<int:pk>/", views.materia_detalle, name="materia_detalle"),
    path("materias/nuevo/", views.materia_crear, name="materia_crear"),
    path("materias/<int:pk>/editar/", views.materia_editar, name="materia_editar"),
    path("materias/<int:pk>/eliminar/", views.materia_eliminar, name="materia_eliminar"),
    path("matriculas/", views.matricula_lista, name="matricula_lista"),
    path("matriculas/<int:pk>/", views.matricula_detalle, name="matricula_detalle"),
    path("matriculas/nuevo/", views.matricula_crear, name="matricula_crear"),
    path("calificaciones/", views.calificacion_lista, name="calificacion_lista"),
    path("calificaciones/<int:pk>/", views.calificacion_detalle, name="calificacion_detalle"),
    path("calificaciones/nuevo/", views.calificacion_crear, name="calificacion_crear"),
    path("calificaciones/<int:pk>/editar/", views.calificacion_editar, name="calificacion_editar"),
    path("calificaciones/<int:pk>/eliminar/", views.calificacion_eliminar, name="calificacion_eliminar"),
    path("asistencias/", views.asistencia_lista, name="asistencia_lista"),
    path("asistencias/nuevo/", views.asistencia_crear, name="asistencia_crear"),
    path("asistencias/<int:pk>/editar/", views.asistencia_editar, name="asistencia_editar"),
    path("asistencias/<int:pk>/eliminar/", views.asistencia_eliminar, name="asistencia_eliminar"),
    path("buscar/", views.buscar, name="buscar"),
    path("reportes/", views.reportes_dashboard, name="reportes_dashboard"),
    path("reportes/boletin/<int:estudiante_id>/", views.reporte_boletin_pdf, name="reporte_boletin_pdf"),
    path("reportes/boletin/", views.reporte_boletin_pdf, name="reporte_boletin_propio"),
    path("reportes/acta/<int:curso_id>/", views.reporte_acta_curso_pdf, name="reporte_acta_curso_pdf"),
    path("reportes/estudiantes_excel/<int:curso_id>/", views.exportar_estudiantes_excel, name="exportar_estudiantes_excel"),
    path("reportes/calificaciones_excel/", views.exportar_calificaciones_excel, name="exportar_calificaciones_excel"),
    path("reportes/asistencias_excel/", views.exportar_asistencias_excel, name="exportar_asistencias_excel"),
    path("panel-promedios/", views.panel_promedios, name="panel_promedios"),
]
